### ISSUE TITLE
AKS fips-enabled image causes error of global mount not existing

### ISSUE THREAD

**Issue by jrudley** [kubernetes-sigs/azurefile-csi-driver#949] opened 2022-03-23 18:37 UTC
**What happened**: Provisioning azure file share via helm chart shows mounting arguments: -t cifs -o mfsymlinks,actimeo=30,dir_mode=0777,file_mode=0777,<masked> //<removed>.file.core.usgovcloudapi.net/pvc-3199f3ca-a4bb-4384-a606-7ae1111ddfa5 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-3199f3ca-a4bb-4384-a606-7ae1111ddfa5/globalmount
Output: mount error(2): No such file or directory

**What you expected to happen**:
pvc mounts

**How to reproduce it**:
create aks cluster 1.22.6 with fips enabled image.

**Anything else we need to know?**: It's the fips enabled image causing this. 

**Environment**:
- CSI Driver version: latest
- Kubernetes version (use `kubectl version`): 1.22.6
- OS (e.g. from /etc/os-release): AKSUbuntu-1804gen2containerd-2022.03.02

**Comment by andyzhangx** [comment] 2022-03-24 06:53
that's by design:
If you are using a Federal Information Processing Standard (FIPS) enabled node pool, the mount will fail because, when FIPS is enabled, it disabled some authentication modules which are preventing the mounting of a CIFS share.  

Pls try with `protocol: nfs` which supports FIPS enabled node.

**Comment by jrudley** [comment] 2022-03-24 12:58
Thanks, I will give it a try tomorrow and report back.

**Comment by andyzhangx** [comment] 2022-04-12 08:53
close this issue since it's by design

**Closed by andyzhangx** 2022-04-12 08:53 UTC
